version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    volumes_from:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  nuxt-app:
    image: nuxt-app
    build: .
    restart: always
    expose:
      - '3000'
    environment:
      - VIRTUAL_HOST=${DOMINIO_HOST}
      - LETSENCRYPT_HOST=${DOMINIO_HOST}

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
