version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  nuxt-app:
    image: dragon-azul-nuxt3-website
    container_name: dragon-azul-website
    restart: always
    build: .
    expose:
      - '3000'
    environment:
      - VIRTUAL_HOST=${DOMINIO_HOST}
      - LETSENCRYPT_HOST=${DOMINIO_HOST}
      - NOTION_API_KEY=${{ NOTION_API_KEY }}
      - APP_ENVIRONMENT=prod
      - NOTION_HOME_ID=${{ NOTION_HOME_ID }}
      - NOTION_ABOUT_ID=${{ NOTION_ABOUT_ID }}
      - NOTION_BLOG_ID=${{ NOTION_BLOG_ID }}
      - NOTION_PORTFOLIO_ID=${{ NOTION_PORTFOLIO_ID }}
      - NOTION_LINK_TREE_ID=${{ NOTION_LINK_TREE_ID }}
      - DEVELOPMENT_STAGE=${{ DEVELOPMENT_STAGE }}
      - PRODUCTION_STAGE=${{ PRODUCTION_STAGE }}

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
