// Generated by https://quicktype.io

export interface LinkResponse {
  linksPages: Link[];
}

export interface Link {
  object: { id: string };
  id: string;
  created_time: string;
  last_edited_time: string;
  created_by: TedBy;
  last_edited_by: TedBy;
  cover?: string;
  icon?: string;
  parent: Parent;
  archived: boolean;
  properties: LinkProperties;
  url: string;
}

export interface TedBy {
  object: string;
  id: string;
}

export interface Parent {
  type: string;
  database_id: string;
}

export interface LinkProperties {
  Link: { id: string };
  Orden: { id: string };
  Name: { id: string };
}
