name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "Major:"
          minor_pattern: "Feat:"
          format: "${major}.${minor}.${patch}"
          
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker build -t $DOCKER_USER/dragon-azul-nuxt3-website:$NEW_VERSION .
          docker build -t $DOCKER_USER/dragon-azul-nuxt3-website:latest .

      - name: Push Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          NEW_VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker push $DOCKER_USER/dragon-azul-nuxt3-website:$NEW_VERSION
          docker push $DOCKER_USER/dragon-azul-nuxt3-website:latest
